name: CI (on pull-request)
run-name: PR from branch ${{ github.ref }}

# Will run CI workflow on an opened or reopened PR for easy reference. For compilation, unit tests, code coverage etc.
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Continuous-Integration:
    name: on pull request
    uses: ./.github/workflows/ci.yml